const permissions = [
  "ticket:create",
  "ticket:read",
  "ticket:update",
  "ticket:delete",
  "task:create",
  "task:read",
  "task:update",
  "task:delete",
  "artifact:create",
  "artifact:read",
  "artifact:update",
  "artifact:delete",
  "phase:create",
  "phase:read",
  "phase:update",
  "phase:delete",
  "project:create",
  "project:read",
  "project:update",
  "project:delete",
  "user:create",
  "user:read",
  "user:update",
  "user:delete",
];
export default permissions;
